In [8]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
from numpy.random import randn

In [9]:
arr = np.arange(9).reshape(3,3)

In [11]:
arr2 = randn(9).reshape(3,3)
print(arr,arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[-1.0630344  -1.23629096  0.42546167]
 [ 1.54305159 -0.39350687 -1.71501251]
 [ 0.20252468  0.41553167  0.00794296]]


In [13]:
# concatenate rows
np.concatenate([arr,arr2])

array([[  0.00000000e+00,   1.00000000e+00,   2.00000000e+00],
       [  3.00000000e+00,   4.00000000e+00,   5.00000000e+00],
       [  6.00000000e+00,   7.00000000e+00,   8.00000000e+00],
       [ -1.06303440e+00,  -1.23629096e+00,   4.25461671e-01],
       [  1.54305159e+00,  -3.93506868e-01,  -1.71501251e+00],
       [  2.02524685e-01,   4.15531674e-01,   7.94296358e-03]])

In [14]:
# concat columns, use axis =1 

np.concatenate([arr,arr2],axis=1)


array([[  0.00000000e+00,   1.00000000e+00,   2.00000000e+00,
         -1.06303440e+00,  -1.23629096e+00,   4.25461671e-01],
       [  3.00000000e+00,   4.00000000e+00,   5.00000000e+00,
          1.54305159e+00,  -3.93506868e-01,  -1.71501251e+00],
       [  6.00000000e+00,   7.00000000e+00,   8.00000000e+00,
          2.02524685e-01,   4.15531674e-01,   7.94296358e-03]])

### Concat in Pandas

In [15]:
ser1 = Series([0,1,2],index=['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])

In [16]:
ser1,ser2

(T    0
 U    1
 V    2
 dtype: int64, X    3
 Y    4
 dtype: int64)

In [17]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [18]:
# This will give a DF 
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [19]:
# We can add multilevel index 
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

## Concat DF

In [20]:
dframe1 = DataFrame(randn(4,3), columns=['X','Y','Z'])
dframe2 = DataFrame(randn(3,3), columns=['Y','Q','X'])

In [23]:
dframe1


X         Y         Z
0  0.427610  1.893219 -0.026021
1  2.762308 -0.694726 -0.004018
2 -0.068061  1.555067  1.294885
3  0.880277  1.361346  0.919710

In [24]:

dframe2

Y         Q         X
0  1.346400 -0.011374  2.445834
1  0.131820  1.949826 -0.069061
2 -0.137751 -1.105530  0.486924

In [25]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.427610  1.893219 -0.026021
1       NaN  2.762308 -0.694726 -0.004018
2       NaN -0.068061  1.555067  1.294885
3       NaN  0.880277  1.361346  0.919710
0 -0.011374  2.445834  1.346400       NaN
1  1.949826 -0.069061  0.131820       NaN
2 -1.105530  0.486924 -0.137751       NaN

In [26]:
# to adjut the reindex by ignoring the index
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN  0.427610  1.893219 -0.026021
1       NaN  2.762308 -0.694726 -0.004018
2       NaN -0.068061  1.555067  1.294885
3       NaN  0.880277  1.361346  0.919710
4 -0.011374  2.445834  1.346400       NaN
5  1.949826 -0.069061  0.131820       NaN
6 -1.105530  0.486924 -0.137751       NaN

In [27]:
url = ' http://pandas.pydata.org/pandas-docs/def/generated/pandas.tools.merge.concat.html'

# Combine DataFrames

In [28]:
npn=np.nan
ser1 = Series([2,npn,4,npn,6,npn], index=['Q','R','S','T','U','V'])

In [29]:
ser1

Q    2.0
R    NaN
S    4.0
T    NaN
U    6.0
V    NaN
dtype: float64

In [30]:
ser2 = Series(np.arange(len(ser1)), dtype=np.float64, index=['Q','R','S','T','U','V'])

In [31]:
ser2

Q    0.0
R    1.0
S    2.0
T    3.0
U    4.0
V    5.0
dtype: float64

In [32]:
# choose value from ser2 where value in ser1 is null
# otherwise, select value from ser1 
Series(np.where(pd.isnull(ser1),ser2,ser1), index=ser1.index)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [33]:
# the other method to combine 
ser1.combine_first(ser2)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [34]:
dframe_odds = DataFrame({'X':[1.,npn,3.,npn],
                        'Y':[npn,5.,npn,7.],
                        'Z':[npn,9.,npn,11]})

In [35]:
dframe_odds

X    Y     Z
0  1.0  NaN   NaN
1  NaN  5.0   9.0
2  3.0  NaN   NaN
3  NaN  7.0  11.0

In [36]:
dframe_evens = DataFrame({'X':[2.,4.,npn,6.,8.],
                         'Y':[npn,10.,12.,14,16.]
                         })

In [37]:
dframe_evens

X     Y
0  2.0   NaN
1  4.0  10.0
2  NaN  12.0
3  6.0  14.0
4  8.0  16.0

In [38]:
dframe_odds.combine_first(dframe_evens)

X     Y     Z
0  1.0   NaN   NaN
1  4.0   5.0   9.0
2  3.0  12.0   NaN
3  6.0   7.0  11.0
4  8.0  16.0   NaN