### Indexing Arrays

In [1]:
import numpy as np

In [6]:
arr_1=np.arange(0,11) 
print(arr_1, arr_1[1])
print(type(arr_1))

[ 0  1  2  3  4  5  6  7  8  9 10] 1
<class 'numpy.ndarray'>


In [7]:
arr_1[:5]=10
print(arr_1)

[10 10 10 10 10  5  6  7  8  9 10]


In [8]:
arr_1=np.arange(0,11) 


In [11]:
slice_of_arr1=arr_1[:5]
slice_of_arr1

array([0, 1, 2, 3, 4])

In [12]:
slice_of_arr1[:]=99
print (slice_of_arr1)
print (arr_1)

[99 99 99 99 99]
[99 99 99 99 99  5  6  7  8  9 10]


In [13]:
# change in slice of array changes original array

#to avoid changes to original arr
arr_1_copy=arr_1.copy()

In [14]:
arr_1_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [20]:
#2d arrays
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
arr_2d[1]  #to specify the row

array([20, 25, 30])

In [22]:
arr_2d[1][0] #index of element, row 1, column 0

20

In [28]:
print(arr_2d[0:2,0:2])

[[ 5 10]
 [20 25]]


In [29]:
print(arr_2d[:2,1:])

[[10 15]
 [25 30]]


In [49]:
arr_2d[:3,1]

array([10, 25, 40])

In [33]:
#fancy indexing
arr_zeros=np.zeros((10,10))

In [34]:
arr_zeros

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [36]:
arr_zeros_len=arr_zeros.shape[1]

In [38]:
arr_zeros_len

10

In [45]:
for i in range(arr_zeros_len):
    arr_zeros[i]=i

In [46]:
arr_zeros

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [47]:
arr_zeros[[5,2,4,1]]

array([[ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

### Transpose Arrays

In [51]:
arr=np.arange(50).reshape(10,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [52]:
#transpose
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [53]:
#dot product
np.dot(arr.T,arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

### Universal Array functions

In [54]:
#universal functions are applied to every element of the array
arr=np.arange(11)
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [55]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [56]:
# creating a normal distn with random numbers
A= np.random.randn(10)
A

array([-1.07639998,  1.89017767, -0.10339158, -1.08109209,  0.0383044 ,
       -0.30018305, -0.2818119 ,  0.12977134, -1.47920106, -0.14111501])

In [58]:
B= np.random.randn(10)
B

array([-0.42428979,  0.84525666,  0.09498489, -0.18193921,  1.29856483,
       -0.83106905,  1.84447727,  0.42636514, -2.00702982, -0.30846972])

In [59]:
#binary functions
np.add(A,B)

array([-1.50068977,  2.73543434, -0.00840669, -1.2630313 ,  1.33686924,
       -1.1312521 ,  1.56266537,  0.55613648, -3.48623088, -0.44958473])

In [60]:
#maximum/minimum will iterate over each element of both arrays and pick the max at the index
np.maximum(A,B)

array([-0.42428979,  1.89017767,  0.09498489, -0.18193921,  1.29856483,
       -0.30018305,  1.84447727,  0.42636514, -1.47920106, -0.14111501])

In [64]:
#to open a link for universal functions docs
import webbrowser
website='http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
webbrowser.open(website)

True

### Array Processing